# Workflow 이름
name: Github Action Study

# Event: 실행되는 시점 설정
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job으로 구성
# 여러 Job은 기본적으로 병렬적으로 수행
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # 실행 환경
    runs-on: ubuntu-latest

    # Step: 특정 작업을 수행하는 단위
    # Job은 여러 Step들로 구성
    steps:
      - name: Hello World
        run: echo "Hello World"

      - name: Hello Github Action
        run: |
          echo "Hello"
          echo "Github Action"

      - name: Github Action 내장 환경 변수 사용
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Repository secrets 추가
        run: | 
          echo ${{ secrets.MY_NAME }}